// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// counter //
// ------- //

#define counter_wrap_target 0
#define counter_wrap 9
#define counter_pio_version 0

static const uint16_t counter_program_instructions[] = {
            //     .wrap_target
    0xa02b, //  0: mov    x, !null                   
    0x0043, //  1: jmp    x--, 3                     
    0x0008, //  2: jmp    8                          
    0x00c1, //  3: jmp    pin, 1                     
    0x0046, //  4: jmp    x--, 6                     
    0x0008, //  5: jmp    8                          
    0x00c8, //  6: jmp    pin, 8                     
    0x0004, //  7: jmp    4                          
    0xa0c1, //  8: mov    isr, x                     
    0x8020, //  9: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program counter_program = {
    .instructions = counter_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config counter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + counter_wrap_target, offset + counter_wrap);
    return c;
}
#endif

